import java.util.HashMap;

public class SpeciesStorage {
    HashMap<Integer, String> species = new HashMap<>();

    public SpeciesStorage() {
        species.put(1, "");
        species.put(2, "Platanus hispanica");
        species.put(3, "Quercus robur");
        species.put(4, "Quercus macrocarpa");
        species.put(5, "Quercus alba");
        species.put(6, "Tilia cordata");
        species.put(7, "Ulmus laevis");
        species.put(8, "Celtis occidentalis");
        species.put(9, "Quercus cerris");
        species.put(10, "Quercus frainetto");
        species.put(11, "Quercus libani");
        species.put(12, "Quercus petraea Mespilifolia");
        species.put(13, "Fagus sylvatica");
        species.put(14, "Sambucus nigra");
        species.put(15, "Taxus baccata");
        species.put(16, "Tilia platyphyllos");
        species.put(17, "Paulownia tomentosa");
        species.put(18, "Pinus sylvestris");
        species.put(19, "Castanea sativa");
        species.put(20, "Quercus coccina");
        species.put(21, "Euodia hupehensis");
        species.put(22, "Quercus bicolor");
        species.put(23, "Abies concolor");
        species.put(24, "Juglans nigra");
        species.put(25, "Quercus petrea");
        species.put(26, "Crataegus");
        species.put(27, "Koelreuteria paniculata");
        species.put(28, "Quercus rubra");
        species.put(29, "Morus alba");
        species.put(30, "Fraxinus excelsior");
        species.put(31, "Juglans cinerea");
        species.put(32, "Populus hybrida");
        species.put(33, "Acer saccharinum");
        species.put(34, "Pyrus communis");
        species.put(35, "Quercus robur Fastigiata");
        species.put(36, "Corylus avellana");
        species.put(37, "Aesculus hippocastanum");
        species.put(38, "Quercus");
        species.put(39, "Camellia japonica");
        species.put(40, "Fagus");
        species.put(41, "Platanus");
        species.put(42, "Pinus");
        species.put(43, "Tilia");
        species.put(44, "Betula");
        species.put(45, "Salix babylonica");
        species.put(46, "Juglans");
        species.put(47, "Salix");
        species.put(48, "Aesculus x carnea");
        species.put(49, "Taxodium distichum");
        species.put(50, "Acer");
        species.put(51, "Malus");
        species.put(52, "Cydonia oblonga");
        species.put(53, "Populus");
        species.put(54, "Fraxinus");
        species.put(55, "Magnolia");
        species.put(56, "Prunus");
        species.put(57, "Prunus domestica subsp. syriaca");
        species.put(58, "Ginkgo biloba");
        species.put(59, "Styphnolobium japonicum");
        species.put(60, "Aesculus");
        species.put(61, "Cornus mas");
        species.put(62, "Tilia x europaea");
        species.put(63, "Catalpa bignonioides");
        species.put(64, "Castanea");
        species.put(65, "Prunus avium");
        species.put(66, "Juglans regia");
        species.put(67, "Larix");
        species.put(68, "Picea");
        species.put(69, "Tsuga mertensiana");
        species.put(70, "Pyrus");
        species.put(71, "Taxus");
        species.put(72, "Liquidambar styraciflua");
        species.put(73, "Platanus x hispanica");
        species.put(74, "Morus nigra");
        species.put(75, "Albizia julibrissin");
        species.put(76, "Robinia pseudoacacia");
        species.put(77, "Celtis");
        species.put(78, "Acer campestre");
        species.put(79, "Liriodendron tulipifera");
        species.put(80, "Populus nigra");
    }
}
